@startuml
skinparam backgroundColor pink
skinparam handwritten false

'title "Updater LLC.の PJT立上げサービス"

partition "Updater LLC.の PJT立上げサービス" {

(*)-->[ビジネスオーナーとの対話の連続]"インセプションデッキの作成"
note right
あるべき姿のヒアリング
ビジネスオーナーとの関係構築
ステークホルダーの認識
目的・理想の共有
end note

"インセプションデッキの作成"-->"ユースケースの列挙"
note right
ユーザーストーリ/業務フローのAsIsを図式化
システム化範囲を検討
ToBe業務フローの図式化・詳細化
ユーザーストーリーの列挙
end note

"ユースケースの列挙"-->"ドメインの整理"
note right
ユースケースの詳細化
出現単語からドメインの整理
システム内部と外部の区別および連携の整理
ERDモデリング（論理〜物理）
end note

"ドメインの整理"-->"システム構成の検討"
note right
規模に応じたハードウェアの選定
隠れたバッチタスクの検討
システム保守ユースケースの列挙・詳細化
end note

"システム構成の検討"-->"スコープ・スケジュール・コスト選択"
note right
ユースケースごとの工数検討
初期費と維持費の検討
設備とユースケースの取捨選択
end note

"スコープ・スケジュール・コスト選択"-->"（稟議等経て予算化）"

"（稟議等経て予算化）"-up->[要再検討の場合]"インセプションデッキの作成"

"（稟議等経て予算化）"-->"キックオフMTG"

"キックオフMTG"-->(*)

}

@enduml
